INSERT INTO provider (code_provider, name) VALUES (null, 'Ambev');
INSERT INTO provider (code_provider, name) VALUES (null, 'Fensa');
INSERT INTO provider (code_provider, name) VALUES (null, 'Heineker');
INSERT INTO provider (code_provider, name) VALUES (null, 'Itaipava');
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Skol', 1);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Polar', 1);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Brahma', 1);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Kaiser', 2);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Bavaria', 2);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Schin', 3);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Itaipava', 4);
INSERT INTO product (code_product,name,id_provider) VALUES (null, 'Antarctica', 1);
INSERT INTO marketplace (code_marketplace, name, gondola, shelf) VALUES (null, 'Carrefour', 10 , 5);
INSERT INTO marketplace (code_marketplace, name, gondola, shelf) VALUES (null, 'Bourbon', 3 , 5);
INSERT INTO marketplace (code_marketplace, name, gondola, shelf) VALUES (null, 'Zaffari', 1 , 5);
INSERT INTO marketplace (code_marketplace, name, gondola, shelf) VALUES (null, 'Nacional', 2 , 3);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Carrefour - Ambev', 70, 1, 1);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Carrefour - Fença', 8, 2, 1);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Carrefour - Heineker', 15, 3, 1);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Carrefour - Itaipava', 0, 4, 1);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Bourbon - Ambev', 65, 1, 2);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Bourbon - Fença', 15, 2, 2);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Bourbon - Heineker', 20, 3, 2);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Bourbon - Itaipava', 0, 4, 2);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Nacional - Ambev', 75, 1, 4);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Nacional - Fença', 5, 2, 4);
INSERT INTO contractprovider (code_contractprovider, name, percentage, id_provider, id_marketplace) VALUES (null, 'Nacional - Heineker', 15, 3, 4);

INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Carrefour - Ambev - Skol', 40, 1, 1);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Bourbon - Ambev - Skol', 40, 1, 5);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Nacional - Ambev - Skol', 40, 1, 9);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Carrefour - Ambev - Polar', 40, 2, 1);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Bourbon - Ambev - Polar', 20, 2, 5);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Nacional - Ambev - Polar', 20, 2, 9);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Carrefour - Ambev - Brahma', 25, 3, 1);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Bourbon - Ambev - Brahma', 50, 3, 5);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Nacional - Ambev - Brahma', 50, 3, 9);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Carrefour - Ambev - Antarctica', 50, 8, 1);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Nacional - Ambev - Antarctica', 50, 8, 9);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Carrefour - Ambev - Antarctica', 50, 8, 2);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Bourbon - Ambev - Antarctica', 50, 8, 6);
INSERT INTO contractproduct (code_contractproduct, name, percentage, id_product, id_contractprovider) VALUES (null, 'Nacional - Ambev - Antarctica', 50, 8, 10);

